---
output: html_document
---

# <span style="color:rgb(129,15,50)">**Dane**</span>

W przeprowadzonej analizie wykorzystane zostały różne kody instrukcji R pochodzące od różnych autorów. W obrębie kategorii A (kody R dla pakietów) pobranych zostało około 400 pierwszych (pierwszych pod względem porządku alfabetycznego) bibliotek ze strony [https://bioconductor.org/](https://bioconductor.org/). Natomiast w celach analizy plików z kategorii B (kody R dla skryptów/analiz/raportów) rozpatrzono autorów ze strony [https://github.com/search?l=&q=language%3AR&type=Users](https://github.com/search?l=&q=language%3AR&type=Users) (pierwsze 10 stron) oraz pobrano ich wszystkie repozytoria z [https://github.com/](https://github.com/) niebędące pakietami.

Na pobranych skryptach wykonana została prosta analiza częstościowa dotycząca bibliotek oraz funkcji. Wszystkie kody napisane w celu jej przeprowadzenia, pliki pomocnicze oraz dane, na których ta analiza się opiera, są dostępne na repozytorium GitHuba pod linkiem [https://github.com/kozaka93/RAdvanced](https://github.com/kozaka93/RAdvanced).

Przykładowo, informacje na temat liczby pakietów, w których wystąpiły poszczególne biblioteki i funkcje, są umieszczone w plikach o nazwach:

- *"biblioteki_czestosc.csv"*
- *"funkcje_czestosc.csv "*
- *"B_biblioteki_czestosc.csv"*
- *"B_funkcje_czestosc.csv "*







